### ISSUE TITLE
stuck on loading screen

### ISSUE THREAD

**Issue by jancborchardt** [shared-stuff/shared-stuff#22]
Returning to the site after staying logged in gives me problems:

```
XHR finished loading: "http://shared-stuff.github.com/partials/friends-stuff.html".
OPTIONS https://5apps.com/storage/jan/sharedstuff/loggedOnTest 200 (OK) in local-libs.min.js:207
PUT https://5apps.com/storage/jan/sharedstuff/loggedOnTest 403 (Forbidden) in loggedOnTest:1
XHR finished loading: "https://5apps.com/storage/jan/sharedstuff/loggedOnTest".
Could not store "loggedOnTest" in "sharedstuff" category in shared-stuff.min.js:6
403 in shared-stuff.min.js:6
```

It works fine in an incognito window where I’m not connected yet.

**Comment by shybyte** [comment]
I will look into it at friday.

**Comment by shybyte** [comment]
Bug can be easily reproduced by modifying localStorage.remoteStorageToken to an invalid value. So this problem occurs when the remoteStorageToken gets invalid. 

2 Workarounds:
- Clear the remoteStorage of all web sites by using the browsers menu. In Firefox: Clear Recent history /Everything/Offline Website Data. In Chrome: Clear browsing data/beginning of time/Cookies, site, and plug-in data
- Clear the remoteStorage of shared stuff in the developer console while being in the sharedstuff app (e.g. by executing "remoteStorage.clear()")

Never happend at my computers, Probably because I often clear my whole browsersing data, because I'm paranoid and my harddisk is small:-)

Thanks for the bug report. I will fix it soon.

**Comment by shybyte** [comment]
The reason was a change in the server's error response in case of invalid authToken from 401 to 403.
Fixed with https://github.com/shared-stuff/shared-stuff/commit/f7660cd66ef221fc86ecbced459504988ca189f5

**Comment by jancborchardt** [comment]
Cool! Now I can share my stuff again, thanks! Would probably also be best to deploy it to sharedstuff.org at 5apps, because without the fix the app does not work a second time.

**Comment by shared-stuff** [comment]
I deploy it right now.

**Comment by shybyte** [comment]
Deployed on sharedstuff.org. It could be that your browser cache keeps the old javascript for some time. So you have to clear the browsers cache in order to benefit from the fix.

**Comment by jancborchardt** [comment]
Works perfectly!
